name: Azure-Policy-as-Code-CD
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
  - cron: "0 0 * * *" #at the end of every day
    
jobs:

  Azure-Policy-as-Code-CD:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: hashicorp/setup-terraform@v1.2.1
      with:
        cli_config_credentials_token: ${{ secrets.TF_TOKEN }}
        terraform_version: 0.13.4
      
    - name: Terraform fmt
      id: fmt
      run: terraform fmt -recursive

    - name: Terraform Init
      id: init
      run: terraform init -backend-config=https://gist.githubusercontent.com/jesseloudon/83ddbe494092ec3d90b0d6d7db41c38c/raw/216581f0240e0404977ec611b286247f75770181/backend.hcl -no-color

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Apply
      id: apply
      run: terraform apply -auto-approve -no-color
